services:
  app:
    image: fireflyiii/core:version-6.1
    restart: always
    env_file: .env
    volumes:
      - type: volume
        source: upload-data
        target: /var/www/html/storage/upload
    ports:
      - name: web-ui
        target: 80
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - db

  db:
    image: mariadb:11.4.2-noble
    restart: always
    env_file: .db.env
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"

volumes:
   upload-data:
   db:
