version: "3.8"

services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin:release-10.8.13-1
    restart: unless-stopped
    environment:
      - PUID=1101
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/jellyfin
        target: /config
        bind:
          create_host_path: true
      - type: tmpfs
        target: /cache
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data/media
        bind:
          create_host_path: true
    networks:
      - media-network
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
        mode: host
