services:
  bind9-authoritative:
    image: internetsystemsconsortium/bind9:9.18
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/bind9-authoritive/confdir
        target: /etc/bind
        bind:
          create_host_path: true
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/bind9-authoritive/workdir
        target: /var/cache/bind
        bind:
          create_host_path: true
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/bind9-authoritive/libdir
        target: /var/lib/bind
        bind:
          create_host_path: true
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/bind9-authoritive/logdir
        target: /var/log
        bind:
          create_host_path: true
    ports:
      # - name: dns-tcp
      - target: 53
        published: ${BIND9_AUTHORITATIVE_DNS_PORT:-54}
        protocol: tcp
        mode: host
      # - name: dns-udp
      - target: 53
        published: ${BIND9_AUTHORITATIVE_DNS_PORT:-54}
        protocol: udp
        mode: host
      # - name: RNDC
      - target: 953
        host_ip: 127.0.0.1
        published: ${BIND9_AUTHORITATIVE_RNDC_PORT:-953}
        protocol: tcp
        mode: host