services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.13.3.4273
    restart: unless-stopped
    environment:
      - PUID=1107
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: volume
        source: prowlarr-appdata
        target: /config
    ports:
      - target: 9696
        published: 9696
        protocol: tcp
        mode: host

volumes:
  prowlarr-appdata:
