version: '3.8'
name: reverse-proxy

services:
  proxy-manager:
    image: jc21/nginx-proxy-manager:2
    restart: unless-stopped
    ports:
      - target: ${NPM_HTTP_PORT:-80}
        published: 80
        protocol: tcp
        mode: host
       
      - target: ${NPM_HTTPS_PORT:-443}
        published: 443
        protocol: tcp
        mode: host
        
      - target: ${NPM_UI_PORT:-81}
        published: 81
        protocol: tcp
        mode: host
    environment:
      DB_MYSQL_HOST: npm-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "npm"
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata folder configured}/nginx-proxy-manager/data
        target: /data
      
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata folder configured}/nginx-proxy-manager/letsencrypt
        target: /etc/letsencrypt
    depends_on:
      - npm-db
    
  npm-db:
    image: jc21/mariadb-aria:10.11.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - type: volume
        source: npm-db
        target: /var/lib/mysql

secrets:
  db_root_password:
    file: ${SECRETS_LOCATION:?No secrets folder configured}/db_root_password.txt
  db_password:
    file: ${SECRETS_LOCATION:?No secrets folder configured}/db_password.txt

volumes:
  npm-db:
    driver: local