services:
  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.1.929
    restart: unless-stopped
    environment:
      - PUID=1104
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: volume
        source: sonarr-appdata
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
        mode: host

volumes:
  sonarr-appdata:
