version: "3.8"

services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:release-1.7.0
    restart: unless-stopped
    environment:
      - PUID=1102
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/jellyseerr
        target: /config
        bind:
          create_host_path: true
    networks:
      - media-network
    ports:
      - target: 5055
        published: 5055
        protocol: tcp
        mode: host
