services:
  autobrr:
    image: ghcr.io/autobrr/autobrr:v1.38
    restart: unless-stopped
    environment:
      - PUID=1108
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: volume
        source: autobrr-appdata
        target: /config
    ports:
      - target: 7474
        published: 7474
        protocol: tcp
        mode: host

volumes:
  autobrr-appdata:
