log:
  level: INFO

api:
  dashboard: true

certificatesresolvers:
  cf-dns-resolver:
    acme:
      dnschallenge:
        provider: cloudflare
      email: "bas_korver@outlook.com"
      keyType: EC384
      storage: /letsencrypt/acme.json
      # Use ISRG Root X2 for staging when I've bought a new phone with an android version of 14 or higher
      # preferredChain: "ISRG Root X2"
      # Use staging server for testing
      caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - redirect_to_xn--krver-jua@file
      tls:
        certResolver: cf-dns-resolver
        domains:
          - main: "korver.it"
            sans: "*.korver.it"
    http3: {}

providers:
  docker:
    exposedbydefault: false
  file:
    directory: /etc/traefik/dynamic-conf.d
    watch: true
