version: '3.8'

services:
  readarr:
    image: ghcr.io/hotio/readarr:nightly-0.3.19.2437
    restart: unless-stopped
    environment:
      - PUID=1106
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/readarr
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
    networks:
      - media-network
    ports:
      - target: 8787
        published: 8787
        protocol: tcp
        mode: host
