## Services:

# Jellyfin
# Jellyseerr

# Radarr
# Sonarr
# Lidarr
# Readarr

# Prowlarr
# Autobrr

# Tdarr
# Bazarr

# Qbittorrent

# Gluetun, needed?

version: "3.8"
name: jellyfleet

services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin:release-10.8.13-1
    restart: unless-stopped
    environment:
      - PUID=1500
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?error}/jellyfin
        target: /config

      - type: tmpfs
        target: /cache
    
      - type: volume
        source: media
        target: /media    
    networks:
      - media-network
    ports:
      - target: 8096
        published: 8096
        protocol: tcp
        mode: host
              
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:release-1.7.0
    restart: unless-stopped
    environment:
      - PUID=1501
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata folder configured}/jellyseerr
        target: /config
    networks:
      - media-network
    ports:
      - target: 5055
        published: 5055
        protocol: tcp
        mode: host

  radarr:
    image: ghcr.io/hotio/radarr:release-5.2.6.8376
    restart: unless-stopped
    environment:
      - PUID=1502
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?error}/radarr
        target: /config
      - type: volume
        source: media
        target: /media
    networks:
      - media-network
    ports:
      - target: 7878
        published: 7878
        protocol: tcp
        mode: host
  
  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.0.748
    restart: unless-stopped
    environment:
      - PUID=1502
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?error}/sonarr
        target: /config
      - type: volume
        source: media
        target: /media
    networks:
      - media-network
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
        mode: host

  lidarr:
    image: ghcr.io/hotio/lidarr:release-2.0.7.3849
    restart: unless-stopped
    environment:
      - PUID=1502
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?error}/lidarr
        target: /config
      - type: volume
        source: media
        target: /media
    networks:
      - media-network
    ports:
      - target: 8686
        published: 8686
        protocol: tcp
        mode: host


  readarr:
    image: ghcr.io/hotio/readarr:nightly-0.3.14.2354
    restart: unless-stopped
    environment:
      - PUID=1502
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?error}/readarr
        target: /config
      - type: volume
        source: media
        target: /media
    networks:
      - media-network
    ports:
      - target: 8787
        published: 8787
        protocol: tcp
        mode: host

  
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-4.6.2
    restart: unless-stopped
    environment:
      - PUID=1503
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?error}/qbittorrent
        target: /config
      - type: volume
        source: media
        target: /media
    networks:
      - media-network
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
        
networks:
  media-network:
    driver: bridge
            
volumes:
  appdata:
    driver: local
  media:
    driver: local