services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-4.6.3
    restart: unless-stopped
    environment:
      - PUID=1110
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: volume
        source: qbittorrent-appdata
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data/torrents
        bind:
          create_host_path: true
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

volumes:
  qbittorrent-appdata: