services:
  bind9-recursive:
    image: internetsystemsconsortium/bind9:9.18
    restart: unless-stopped
    ports:
      # - name: RNDC
      - target: 953
        host_ip: 127.0.0.1
        published: ${BIND9_RECURSIVE_RNDC_PORT:-954}
        protocol: tcp
        mode: host