services:
  lidarr:
    image: ghcr.io/hotio/lidarr:release-2.1.7.4030
    restart: unless-stopped
    environment:
      - PUID=1105
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: volume
        source: lidarr=appdata
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
    ports:
      - target: 8686
        published: 8686
        protocol: tcp
        mode: host

volumes:
  lidarr-appdata:
