version: '3.8'

services:
  radarr:
    image: ghcr.io/hotio/radarr:release-5.3.6.8612
    restart: unless-stopped
    environment:
      - PUID=1103
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/radarr
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
    networks:
      - media-network
    ports:
      - target: 7878
        published: 7878
        protocol: tcp
        mode: host
