services:
  radarr:
    image: ghcr.io/hotio/radarr:release-5.3.6.8612
    restart: unless-stopped
    environment:
      - PUID=1103
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: volume
        source: radarr-appdata
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
    ports:
      - target: 7878
        published: 7878
        protocol: tcp
        mode: host

volumes:
  radarr-appdata:
