services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:release-1.7.0
    restart: unless-stopped
    environment:
      - PUID=1102
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: volume
        source: jellyseerr-appdata
        target: /config
    ports:
      - target: 5055
        published: 5055
        protocol: tcp
        mode: host

volumes:
  jellyseerr-appdata: