services:
  adguard-home:
    image: adguard/adguardhome:v0.107.44
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/adguard/workdir
        target: /opt/adguardhome/work
        bind:
          create_host_path: true
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/adguard/confdir
        target: /opt/adguardhome/conf
        bind:
          create_host_path: true
    network_mode: "host"
    ports:
      # - name: dns-tcp
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      # - name: dns-udp
      - target: 53
        published: 53
        protocol: udp
        mode: host
      # - name: dashboard-http
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      # - name: configuration-port
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
